### ISSUE TITLE
Is it possible to override the normalizePath from the config?

### ISSUE THREAD

**Issue by ayashjorden** [jochen-schweizer/express-prom-bundle#15]
Hello,
In the [documentation](https://github.com/jochen-schweizer/express-prom-bundle#more-details-on-includepath-option) it says that one needs to override the original `normalizePath` function to add custom logic.

Is it possible to do so also by specifying a `normalizePath` key in the config passed to the `promBundle` function call?
for example: (my config, in the code i call `promBundle(config.get("prometheus"))`)
```
    prometheus:
        includeMethod: true
        includePath: true
        promClient:
            collectDefaultMetrics:
                timeout: 1000
         normalizePath:
             '\/auth\/token\/.*$': '/auth/token/*' => this will get magically parsed and added to the paths-to-normalize
```

Thank you,
Yarden
